;METADATA=(Diff=true, UseCommands=true)
[/Script/OnlineSubsystemUtils.IpNetDriver]
MaxClientRate=600000
MaxInternetClientRate=600000
NetServerMaxTickRate=60
LanServerMaxTickRate=60

[OnlineSubsystem]
ServerName=[FR/EUW] La Confrérie | discord.gg/eYRbMVG
